"""Solidity library generator for on-chain pixel art storage."""


def generate_solidity_library(
    name: str,
    bitmap: bytes,
    size: int,
    color: str = "000000",
) -> str:
    """
    Generate Solidity library matching existing image-to-1bit.js output format.

    Args:
        name: Base name for the library (will be capitalized)
        bitmap: Packed bitmap bytes
        size: Image dimension (128 or 256)
        color: Foreground color as hex string (without #)

    Returns:
        Solidity library source code
    """
    lib_name = name[0].upper() + name[1:] + f"{size}Mono"
    hex_bitmap = bitmap.hex()
    total_bytes = len(bitmap)
    render_func = "render1bit256" if size == 256 else "render1bit128"

    return f'''// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {{PixelArtRenderer}} from "./PixelArtRenderer.sol";

/**
 * @title {lib_name}
 * @dev On-chain pixel art storage ({size}x{size}, monochrome 1-bit)
 * @notice Generated by PBSEP-256 - Do not edit manually
 */
library {lib_name} {{
    /// @notice Foreground color (RGB)
    function getColor() internal pure returns (bytes3) {{
        return hex"{color}";
    }}

    /// @notice {size}x{size} pixel bitmap, 1-bit ({total_bytes} bytes)
    function getBitmap() internal pure returns (bytes memory) {{
        return hex"{hex_bitmap}";
    }}

    /// @notice Render as SVG string
    function getSVG() internal pure returns (string memory) {{
        return PixelArtRenderer.{render_func}(getColor(), getBitmap());
    }}
}}
'''
