#!/bin/bash
# Deploy BTCNFT Protocol contracts (local Anvil only)
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLI_DIR="$(dirname "$SCRIPT_DIR")"
PROJECT_DIR="$(dirname "$CLI_DIR")"
ENV_FILE="$CLI_DIR/.env"

cd "$PROJECT_DIR"

echo "=== BTCNFT Protocol Setup ==="

# Kill existing Anvil if running
if pgrep -f "anvil" > /dev/null; then
    echo "Stopping existing Anvil instance..."
    pkill -f "anvil" || true
    sleep 2
fi

echo "Starting Anvil..."
anvil --block-time 1 > /dev/null 2>&1 &
ANVIL_PID=$!
sleep 3

if ! kill -0 $ANVIL_PID 2>/dev/null; then
    echo "Error: Failed to start Anvil" >&2
    exit 1
fi
echo "Anvil started (PID: $ANVIL_PID)"

# Default Anvil private key
export PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

echo "Deploying contracts..."
OUTPUT=$(forge script script/Deploy.s.sol:Deploy --rpc-url http://localhost:8545 --broadcast 2>&1)

# Parse deployment addresses
WBTC=$(echo "$OUTPUT" | grep "WBTC:" | awk '{print $2}')
TREASURE=$(echo "$OUTPUT" | grep "TREASURE:" | awk '{print $2}')
BTC_TOKEN=$(echo "$OUTPUT" | grep "BTC_TOKEN:" | awk '{print $2}')
VAULT=$(echo "$OUTPUT" | grep "VAULT:" | awk '{print $2}')

if [[ -z "$VAULT" ]]; then
    echo "Error: Failed to parse deployment addresses" >&2
    echo "$OUTPUT" >&2
    exit 1
fi

# Write environment file
cat > "$ENV_FILE" << EOF
# BTCNFT Protocol - Local Environment
# Generated by: ./btcnft setup

RPC_URL=http://localhost:8545
PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

# Contract Addresses
WBTC=$WBTC
TREASURE=$TREASURE
BTC_TOKEN=$BTC_TOKEN
VAULT=$VAULT

# Anvil Process
ANVIL_PID=$ANVIL_PID
EOF

echo ""
echo "=== Deployment Complete ==="
echo "WBTC:      $WBTC"
echo "TREASURE:  $TREASURE"
echo "BTC_TOKEN: $BTC_TOKEN"
echo "VAULT:     $VAULT"
echo ""
echo "Environment saved to: $ENV_FILE"
echo ""
echo "To stop Anvil: kill $ANVIL_PID"
echo ""
echo "Next steps:"
echo "  ./btcnft mint <treasure_id> <btc_amount_satoshis>"
echo "  ./btcnft status <vault_token_id>"
